name       : brlaser
version    : 6.2.5
release    : 2
source     :
    - https://github.com/Owl-Maintain/brlaser/archive/refs/tags/v6.2.5.tar.gz : 574cd43002a2b526d6888a2e3cfd7a648cdbb3896511ab7f8952aab3e0bfb58c
license    : GPL-2.0-or-later
component  : drivers.printer
summary    : Open-source CUPS driver for monochrome Brother laser printers
description: |
    brlaser is an open-source CUPS driver designed specifically for Brother monochrome laser printers and multi-function devices
strip      : no
builddeps  :
    - cups-devel
rundeps    :
    - ghostscript
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
