name       : brlaser
version    : 6.2.6
release    : 3
source     :
    - https://github.com/Owl-Maintain/brlaser/archive/refs/tags/v6.2.6.tar.gz : 551f85a234c75c52c52bb76f379eb458ebc7bd7164d55763d97e197a0ad47f6d
homepage   : https://github.com/Owl-Maintain/brlaser
license    : GPL-2.0-or-later
component  : drivers.printer
summary    : Open-source CUPS driver for monochrome Brother laser printers
description: |
    brlaser is an open-source CUPS driver designed specifically for Brother monochrome laser printers and multi-function devices
strip      : no
builddeps  :
    - cups-devel
rundeps    :
    - ghostscript
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
